name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Install dependencies
        run: npm ci

      - name: Zip and deploy to Lambda
        run: |
          zip -r deploy.zip . -x '.git/*' -x '.github/*'
          
          RETRY_COUNT=5
          RETRY_INTERVAL=10
          for i in $(seq 1 $RETRY_COUNT); do
            aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:537757446889:function:lambda-monster-inventory --zip-file fileb://deploy.zip && break
            if [ "$i" -eq "$RETRY_COUNT" ]; then
              echo "Max retries reached. Exiting."
              exit 1
            fi
            echo "Retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          done

          for i in $(seq 1 $RETRY_COUNT); do
            aws lambda update-function-configuration --function-name arn:aws:lambda:us-east-1:537757446889:function:lambda-monster-inventory --handler src/handler.handler && break
            if [ "$i" -eq "$RETRY_COUNT" ]; then
              echo "Max retries reached. Exiting."
              exit 1
            fi
            echo "Retrying in $RETRY_INTERVAL seconds..."
            sleep $RETRY_INTERVAL
          done
